apiVersion: apps/v1
kind: Deployment
metadata:
  name: bl-payment-deployment
  labels:
    app: bl-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bl-payment
  template:
    metadata:
      labels:
        app: bl-payment
    spec:
      containers:
      - name: bl-payment
        image: CHANGEME
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m" 
        envFrom:
        - configMapRef:
            name: app-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: bl-payment-service
spec:
  selector:
    app: bl-payment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000